### 주민 등록 API
POST localhost:8080/residents
Content-Type: application/json

{
  "name": "테스트",
  "residentRegistrationNumber": "000101-*******",
  "genderCode": "남",
  "birthDate": "2000-01-01T00:00:00",
  "birthPlaceCode": "병원",
  "registrationBaseAddress": "서울특별시"
}

### 주민 수정 API
PUT localhost:8080/residents/1
Content-Type: application/json

{
}